# Generated by Django 3.0.8 on 2020-07-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200709_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
