# Generated by Django 3.0.8 on 2020-07-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200709_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='categoria',
            new_name='categoriadotipo',
        ),
    ]
