# Generated by Django 3.0.8 on 2020-07-09 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200709_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='datademodificacao',
            new_name='datadefabricacao',
        ),
        migrations.AddField(
            model_name='categoria',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tipo',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='produto',
            name='datadecriacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
