# Generated by Django 3.0.8 on 2020-07-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200709_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='datadefabricacao',
            field=models.CharField(max_length=20),
        ),
    ]
