# Generated by Django 3.0.8 on 2020-07-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200709_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='datadefabricacao',
            field=models.DateField(max_length=20),
        ),
    ]
